server:
      port: 8084

spring:
  application:
    name: abcmsc-provider-depart
  profiles: dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test02?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  #指定当前微服务对象暴露的名称
  application:
    name: syjmsc-provider-depart


logging:
  pattern:
    console: level-%level %msg%n
  level:
      root: info
      org: hibernate:info
      org.hibernate.type.descriptor.sql.BasicBinder: trace
      org.hibernate.type.descriptor.sql.BasicExtractor: trace
      com.syj.provider: debug


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8400/eureka


info:
    company.name: www.syj.com
    company.addr: China Beijing
    company.tel: 12345
    app.name: syj
    app.desc: mic-server-cloud


---
server:
      port: 8085

spring:
  application:
    name: abcmsc-provider-depart
  profiles: test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test03?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  #指定当前微服务对象暴露的名称
  application:
    name: syjmsc-provider-depart


logging:
  pattern:
    console: level-%level %msg%n
  level:
      root: info
      org: hibernate:info
      org.hibernate.type.descriptor.sql.BasicBinder: trace
      org.hibernate.type.descriptor.sql.BasicExtractor: trace
      com.syj.provider: debug


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka


info:
    company.name: www.syj.com
    company.addr: China Beijing
    company.tel: 12345
    app.name: syj
    app.desc: mic-server-cloud

