server:
      port: 7070
spring:
 profiles:dev
 application:
  name: abcmsc-comsumer-depart

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8400/eureka

---

server:
      port: 9090
spring:
 profiles:test
 application:
  name: abcmsc-comsumer-depart

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8500/eureka
